feat: add gists
Zhabrikoff/TestGuru pull request #13
Opened 2024-08-20 18:23 UTC by Zhabrikoff

2024-08-21 07:32 UTC, VidgarVii requested changes

2024-08-21 07:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  def gist
Повод вспомнить про REST.
Gist это ресурс. Значит согласно rails way и REST для создания ресурса и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2024-08-21 07:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if result
тут проверяется только наличие какого-то результата, а не его успешность или корректность.
result может содержать цифру 1. И при этом будет попытка записи гиста в бд

есть стандартный принятый подход для сервисов

if result.success?

2024-08-21 07:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +        { notice: result }
тут явно проблемы с логикой. Выше мы используем result для проверки в условном операторе, потом передаём в url при создании гист в бд. А теперь вставляем этот result во flash сообщение. Что это за result такой?)

2024-08-21 07:32 UTC, VidgarVii commented on app/services/git_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_ACCESS_TOKEN)
end
```

2024-08-21 07:32 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +class GitHubClient
Зачем нужна эта обертка?) Она не делает ничего полезного - можно напрямую с Octokit работать. И не надо будет тестировать отдельный класс.
GistQuestionService уже является как бы адаптером над Octokit

2024-08-21 07:32 UTC, VidgarVii commented on app/services/git_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2024-08-21 07:32 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +    end
в итоге чтобы понять что содержит result  в контроллере надо еще нырнуть в гем Octokit::Client. И как пользоваться сервисов создания гист не совсем понятно. Так как присутствуют сквозные зависимости м/е объектами. Некого рода спагети код.
Метод call в  GitQuestionService должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2024-08-23 07:42 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +        Gist.create(url: result.html_url, user: current_user, question: @test_passage.current_question)
`current_user.gists.create(...)` можно еще так, через ассоциации

2024-08-26 16:32 UTC, merged